/*
Yatzy-spel för 2 spelare TEST
 */
package yatzy;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jennywong
 */
public class Yatzy extends javax.swing.JFrame {
    
    public Yatzy() {
        initComponents();
    }
    //skapa en array med fem tärningar
    private int[] dicePosition = new int[5];
    int value, count; //store tärningvärde
    final int ETTOR = 1;
    final int TVAOR = 2;
    final int TREOR = 3;
    final int FYROR = 4;
    final int FEMOR = 5;
    final int SEXOR = 6;
    final int ANTAL_DICE = 5;
    final int BONUS = 35;
    final int LITEN_STEGE = 15;
    final int STOR_STEGE = 20;
    final int YATZY = 50;
    
    //spara tärningsvärden
    //private ArrayList<Integer> savedValue = new ArrayList<>();
    private ArrayList<Integer> sumLeft = new ArrayList<>();
    private ArrayList<Integer> sumRight = new ArrayList<>();
    //private ArrayList<Integer> score = new ArrayList<>();
    
    
    int diceCount = 0;
    private int nPlayers;
    
    
    private void Kasta(){
        value = (int) (Math.random() * 6 + 1);
        }
    
    private void FirstRoll(){
        for (int n = 0; n < ANTAL_DICE; n++) {
            Kasta();
            dicePosition[n] = value;     //tilldelar värdet
        }
        //visa diceValue på displayen(tärningsbutton)
        for (int m = 0; m < ANTAL_DICE; m++) {
            if (m == 0) {
                tglbtnDice1.setText("" + dicePosition[m]);
            }
            if (m == 1) {
                tglbtnDice2.setText("" + dicePosition[m]);
            }
            if (m == 2) {
                tglbtnDice3.setText("" + dicePosition[m]);
            }
            if (m == 3) {
                tglbtnDice4.setText("" + dicePosition[m]);
            }
            if (m == 4) {
                tglbtnDice5.setText("" + dicePosition[m]);
            }
            
            diceCount = 1;
        }
    }
    
    private void SecondAndThirdRoll(){
        //klickade tärningar kastas om
        if (tglbtnDice1.isSelected()) {
            Kasta();
            dicePosition[0] = value;
        }
        if (tglbtnDice2.isSelected()) {
            Kasta();
            dicePosition[1] = value;
        }
        if (tglbtnDice3.isSelected()) {
            Kasta();
            dicePosition[2] = value;
        }
        if (tglbtnDice4.isSelected()) {
            Kasta();
            dicePosition[3] = value;
        }
        if (tglbtnDice5.isSelected()) {
            Kasta();
            dicePosition[4] = value;
        }
        
        //visa på displayen
        for (int m = 0; m < ANTAL_DICE; m++) {
            if (m == 0) {
                tglbtnDice1.setText("" + dicePosition[m]);
            }
            if (m == 1) {
                tglbtnDice2.setText("" + dicePosition[m]);
            }
            if (m == 2) {
                tglbtnDice3.setText("" + dicePosition[m]);
            }
            if (m == 3) {
                tglbtnDice4.setText("" + dicePosition[m]);
            }
            if (m == 4) {
                tglbtnDice5.setText("" + dicePosition[m]);
            }
        }
        diceCount += 1;
    }
      
    /*
    private void PlayGame(){
        for (int turns = 0; turns < 15; turns++) {
            for (int player = 0; player < nPlayers; player++) {
                FirstRoll(player);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnKasta = new javax.swing.JButton();
        tglbtnDice1 = new javax.swing.JToggleButton();
        tglbtnDice2 = new javax.swing.JToggleButton();
        tglbtnDice3 = new javax.swing.JToggleButton();
        tglbtnDice4 = new javax.swing.JToggleButton();
        tglbtnDice5 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnEttor = new javax.swing.JButton();
        btnTvaor = new javax.swing.JButton();
        btnTreor = new javax.swing.JButton();
        btnFyror = new javax.swing.JButton();
        btnFemor = new javax.swing.JButton();
        btnSexor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfEttor = new javax.swing.JTextField();
        txfEttorS2 = new javax.swing.JTextField();
        txfTvaorS2 = new javax.swing.JTextField();
        txfTvaor = new javax.swing.JTextField();
        txfTreorS2 = new javax.swing.JTextField();
        txfTreor = new javax.swing.JTextField();
        txfFyrorS2 = new javax.swing.JTextField();
        txfFyror = new javax.swing.JTextField();
        txfFemmorS2 = new javax.swing.JTextField();
        txfFemor = new javax.swing.JTextField();
        txfSexorS2 = new javax.swing.JTextField();
        txfSexor = new javax.swing.JTextField();
        txfSummaS2 = new javax.swing.JTextField();
        txfSumma = new javax.swing.JTextField();
        txfBonusS2 = new javax.swing.JTextField();
        txfBonus = new javax.swing.JTextField();
        btnEttPar = new javax.swing.JButton();
        btnTriss = new javax.swing.JButton();
        btnFyrtal = new javax.swing.JButton();
        btnLStege = new javax.swing.JButton();
        btnSStege = new javax.swing.JButton();
        btnYatzy = new javax.swing.JButton();
        btnKak = new javax.swing.JButton();
        btnChans = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblS2Left = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        txfChans = new javax.swing.JTextField();
        txfEttParS2 = new javax.swing.JTextField();
        txfTvaParS2 = new javax.swing.JTextField();
        txfTvaPar = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        txfTriss = new javax.swing.JTextField();
        txfEttPar = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        txfFyrtal = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        txfLStege = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        txfSStege = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        txfKak = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        txfYatzy = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        txfTotal = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        btnTvaPar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblS2Right = new javax.swing.JLabel();
        btnStarta = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKasta.setText("Kasta");
        btnKasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKastaActionPerformed(evt);
            }
        });

        tglbtnDice1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        tglbtnDice2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        tglbtnDice3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        tglbtnDice4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        tglbtnDice5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglbtnDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglbtnDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglbtnDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglbtnDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglbtnDice5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKasta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglbtnDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnDice5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKasta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Klicka på tärning för att kasta om den");

        btnEttor.setText("Ettor");
        btnEttor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttorActionPerformed(evt);
            }
        });

        btnTvaor.setText("Tvåor");
        btnTvaor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaorActionPerformed(evt);
            }
        });

        btnTreor.setText("Treor");
        btnTreor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreorActionPerformed(evt);
            }
        });

        btnFyror.setText("Fyror");
        btnFyror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrorActionPerformed(evt);
            }
        });

        btnFemor.setText("Femor");
        btnFemor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemorActionPerformed(evt);
            }
        });

        btnSexor.setText("Sexor");
        btnSexor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSexorActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Summa");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bonus");

        txfEttor.setEditable(false);
        txfEttor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfEttorS2.setEditable(false);
        txfEttorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEttorS2.setEnabled(false);

        txfTvaorS2.setEditable(false);
        txfTvaorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTvaorS2.setEnabled(false);

        txfTvaor.setEditable(false);
        txfTvaor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfTreorS2.setEditable(false);
        txfTreorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTreorS2.setEnabled(false);

        txfTreor.setEditable(false);
        txfTreor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfFyrorS2.setEditable(false);
        txfFyrorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfFyrorS2.setEnabled(false);

        txfFyror.setEditable(false);
        txfFyror.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfFemmorS2.setEditable(false);
        txfFemmorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfFemmorS2.setEnabled(false);

        txfFemor.setEditable(false);
        txfFemor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfSexorS2.setEditable(false);
        txfSexorS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSexorS2.setEnabled(false);

        txfSexor.setEditable(false);
        txfSexor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfSummaS2.setEditable(false);
        txfSummaS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSummaS2.setEnabled(false);

        txfSumma.setEditable(false);
        txfSumma.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfBonusS2.setEditable(false);
        txfBonusS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfBonusS2.setEnabled(false);

        txfBonus.setEditable(false);
        txfBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEttPar.setText("Ett par");
        btnEttPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttParActionPerformed(evt);
            }
        });

        btnTriss.setText("Triss");
        btnTriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrissActionPerformed(evt);
            }
        });

        btnFyrtal.setText("Fyrtal");
        btnFyrtal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrtalActionPerformed(evt);
            }
        });

        btnLStege.setText("Liten stege");
        btnLStege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLStegeActionPerformed(evt);
            }
        });

        btnSStege.setText("Stor stege");
        btnSStege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSStegeActionPerformed(evt);
            }
        });

        btnYatzy.setText("Yatzy");
        btnYatzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatzyActionPerformed(evt);
            }
        });

        btnKak.setText("Kåk");
        btnKak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKakActionPerformed(evt);
            }
        });

        btnChans.setText("Chans");
        btnChans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChansActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Totalt");

        jLabel4.setText("Spelare 1");

        lblS2Left.setText("Spelare 2");
        lblS2Left.setEnabled(false);

        jTextField24.setEditable(false);
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setEnabled(false);

        txfChans.setEditable(false);
        txfChans.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfEttParS2.setEditable(false);
        txfEttParS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEttParS2.setEnabled(false);

        txfTvaParS2.setEditable(false);
        txfTvaParS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTvaParS2.setEnabled(false);

        txfTvaPar.setEditable(false);
        txfTvaPar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField12.setEditable(false);
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setEnabled(false);

        txfTriss.setEditable(false);
        txfTriss.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txfEttPar.setEditable(false);
        txfEttPar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField15.setEditable(false);
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setEnabled(false);

        txfFyrtal.setEditable(false);
        txfFyrtal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField27.setEditable(false);
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setEnabled(false);

        txfLStege.setEditable(false);
        txfLStege.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField29.setEditable(false);
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setEnabled(false);

        txfSStege.setEditable(false);
        txfSStege.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField31.setEditable(false);
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setEnabled(false);

        txfKak.setEditable(false);
        txfKak.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField33.setEditable(false);
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField34.setEditable(false);
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setEnabled(false);

        jTextField35.setEditable(false);
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField36.setEditable(false);
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setEnabled(false);

        txfYatzy.setEditable(false);
        txfYatzy.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField38.setEditable(false);
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setEnabled(false);

        txfTotal.setEditable(false);
        txfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField42.setEditable(false);
        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField42.setEnabled(false);

        btnTvaPar.setText("Två par");
        btnTvaPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaParActionPerformed(evt);
            }
        });

        jLabel7.setText("Spelare 1");

        lblS2Right.setText("Spelare 2");
        lblS2Right.setEnabled(false);

        btnStarta.setText("Klicka här för att starta");
        btnStarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lblS2Left)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSexor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFemor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txfSummaS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txfBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txfBonusS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfSexorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfFyrorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfFemor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfFemmorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(btnFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEttor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTreor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTvaor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfEttorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfTvaorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txfTreor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txfTreorS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFyrtal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4))
                                    .addComponent(btnLStege, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSStege, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnChans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnYatzy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStarta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfEttParS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfTvaParS2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfSStege, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfLStege, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblS2Right))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfChans, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStarta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS2Left)
                    .addComponent(jLabel4)
                    .addComponent(lblS2Right)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnTriss)
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChans)
                            .addComponent(txfChans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEttor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfEttor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfEttorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfTvaorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTvaor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTreor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfTreorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTreor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFyror)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfFyror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfFyrorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfFemor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfFemmorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFemor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfSexor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfSexorS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfSummaS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnKak)
                                            .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(btnSexor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfBonusS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfEttPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfEttParS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfTvaPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfTvaParS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTvaPar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfTriss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFyrtal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfLStege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnLStege, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txfSStege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSStege)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEttPar)))
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnYatzy)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartaActionPerformed
         String[] antalSpelare = { "1", "2"};
        String input = (String) JOptionPane.showInputDialog(null, "Välj antal spelare",
        "", JOptionPane.QUESTION_MESSAGE, null, 
        antalSpelare, // Array of choices
        antalSpelare[1]); // Initial choice
        
    }//GEN-LAST:event_btnStartaActionPerformed

    private void btnKastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKastaActionPerformed
        if (diceCount == 0) {
            FirstRoll();
        } else if (diceCount == 1){
            SecondAndThirdRoll();
        } else {
            SecondAndThirdRoll();
            btnKasta.setEnabled(false);
        }
        //om txf för ettor-sexor inte är tomma, visa totalpoäng+bonus för vänstra sidan av scorecard
        if (txfLeftisAllFilled() == true){
            //visar summan
            sumLeft();
            txfSumma.setText("" + sumLeft());
            //visar bonus
            if (Bonus() == true) {
                txfBonus.setText("" + BONUS);
            } else {
               txfBonus.setText("" + 0); 
            } 
        }
        //visa totalpoängen när alla kategorier är poängsatta
        if (txfLeftisAllFilled() == true && txfRightisAllFilled() == true){
            //visar summan)
            txfTotal.setText("" + (sumRight() + sumLeft()));
            
        }
        
    }//GEN-LAST:event_btnKastaActionPerformed

    private void btnEttorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttorActionPerformed
        //räkna hur många ettor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == ETTOR){
                count++;
            }
        }
        //visa resultat på displayen
        txfEttor.setText("" + (count*ETTOR));
        
        //spara värdet i sum-arraylist
        sumLeft.add(count*ETTOR);
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnEttor.setEnabled(false);
    }//GEN-LAST:event_btnEttorActionPerformed

    private void btnTvaorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaorActionPerformed
        //räkna hur många tvåor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == TVAOR){
                count++;
            }
        }
        //visa resultat på displayen
        txfTvaor.setText("" + (count*TVAOR));
        
        //spara värdet i sum-arraylist
        sumLeft.add(count*TVAOR);
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnTvaor.setEnabled(false);
    }//GEN-LAST:event_btnTvaorActionPerformed

    private void btnTreorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreorActionPerformed
        //räkna hur många tvåor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == TREOR){
                count++;
            }
        }
        //visa resultat på displayen
        txfTreor.setText("" + (count*TREOR));
        
        //spara värdet i sum-arraylist
        sumLeft.add(count*TREOR);
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnTreor.setEnabled(false);
    }//GEN-LAST:event_btnTreorActionPerformed

    private void btnFyrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrorActionPerformed
        //räkna hur många tvåor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == FYROR){
                count++;
            }
        }
        //visa resultat på displayen
        txfFyror.setText("" + (count*FYROR));
        
        //spara värdet i sum-arraylist
        sumLeft.add(count*FYROR);
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnFyror.setEnabled(false);
    }//GEN-LAST:event_btnFyrorActionPerformed

    private void btnFemorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemorActionPerformed
        //räkna hur många tvåor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == FEMOR){
                count++;
            }
        }
        //visa resultat på displayen
        txfFemor.setText("" + (count*FEMOR));

        //spara värdet i sum-arraylist
        sumLeft.add(count*FEMOR);

        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnFemor.setEnabled(false);
    }//GEN-LAST:event_btnFemorActionPerformed

    private void btnSexorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexorActionPerformed
        //räkna hur många tvåor tärningskastet har
        for (int i = 0; i < ANTAL_DICE; i++) {
            if (dicePosition[i] == SEXOR){
                count++;
            }
        }
        //visa resultat på displayen
        txfSexor.setText("" + (count*SEXOR));

        //spara värdet i sum-arraylist
        sumLeft.add(count*SEXOR);

        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnSexor.setEnabled(false);
    }//GEN-LAST:event_btnSexorActionPerformed

    private void btnEttParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttParActionPerformed
        qualifyRight("ettPar");
        txfEttPar.setText("" + qualifyRight("ettPar"));
        
        //spara poängen
        sumRight.add(qualifyRight("ettPar"));
        
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnEttPar.setEnabled(false);
    }//GEN-LAST:event_btnEttParActionPerformed

    private void btnTvaParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaParActionPerformed
        qualifyRight("tvaPar");
        txfTvaPar.setText("" + qualifyRight("tvaPar"));
        
        //spara poängen
        sumRight.add(qualifyRight("tvaPar"));
        
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnTvaPar.setEnabled(false);
    }//GEN-LAST:event_btnTvaParActionPerformed

    private void btnTrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrissActionPerformed
        qualifyRight("triss");
        txfTriss.setText("" + qualifyRight("triss"));  
        
        //spara poängen
        sumRight.add(qualifyRight("triss"));
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnTriss.setEnabled(false);
    }//GEN-LAST:event_btnTrissActionPerformed

    private void btnFyrtalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrtalActionPerformed
        qualifyRight("fyrtal");
        txfFyrtal.setText("" + qualifyRight("fyrtal"));
        
        //spara poängen
        sumRight.add(qualifyRight("fyrtal"));
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnFyrtal.setEnabled(false);
    }//GEN-LAST:event_btnFyrtalActionPerformed

    private void btnLStegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLStegeActionPerformed
        //Ok, funkar!
        BubbelSortera(dicePosition);
        if (dicePosition[0] == 1 && dicePosition[1] == 2 && dicePosition[2] == 3 && dicePosition[3] == 4
                && dicePosition[4] == 5) {
            txfLStege.setText("" + LITEN_STEGE);
            sumRight.add(LITEN_STEGE);
        } else {
            txfLStege.setText("" + 0);
        }
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnLStege.setEnabled(false);
    }//GEN-LAST:event_btnLStegeActionPerformed

    private void btnSStegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSStegeActionPerformed
        //Ok, funkar!
        
        BubbelSortera(dicePosition);

        if (dicePosition[0] == 2 && dicePosition[1] == 3 && dicePosition[2] == 4 && dicePosition[3] == 5
                && dicePosition[4] == 6) {
            txfSStege.setText("" + STOR_STEGE);
            sumRight.add(STOR_STEGE);
        } else {
            txfSStege.setText("" + 0);
        }
        
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnSStege.setEnabled(false);
    }//GEN-LAST:event_btnSStegeActionPerformed

    private void btnKakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKakActionPerformed
        qualifyRight("kak");
        txfKak.setText("" + qualifyRight("kak"));
        
        //spara poängen
        sumRight.add(qualifyRight("kak"));
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnKak.setEnabled(false);
    }//GEN-LAST:event_btnKakActionPerformed

    private void btnChansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChansActionPerformed
        //OK, funkar!
        //räkna ut totalpoängen för tärningskastet
        int chans = 0;
        for (int i = 0; i < dicePosition.length; i++) {
            chans += dicePosition[i];
        }
        txfChans.setText("" + chans);
        
        //spara värdet
        sumRight.add(chans);
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnChans.setEnabled(false);
    }//GEN-LAST:event_btnChansActionPerformed

    private void btnYatzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatzyActionPerformed
        qualifyRight("yatzy");
        txfYatzy.setText("" + qualifyRight("yatzy"));
        
        //spara poängen
        sumRight.add(qualifyRight("yatzy"));
        
        //aktiverar möjligheten att göra ett nytt kast
        btnKasta.setEnabled(true);
        count = 0;
        diceCount = 0;
        diceButtonUnselected();
        btnYatzy.setEnabled(false);
    }//GEN-LAST:event_btnYatzyActionPerformed
    
    //Metod för att räkna ut totalpoängen för högra sidan av scorecard,
    private int sumLeft(){
        int sum = 0;
        for (int i = 0; i < sumLeft.size(); i++) {
           sum += sumLeft.get(i);
        }
        return sum;
    }
    
    //Metod för att räkna ut totalpoängen för högra sidan av scorecard
    private int sumRight(){
        int sum = 0;
        for (int i = 0; i < sumRight.size(); i++) {
           sum += sumRight.get(i);
        }
        return sum;
    }
    
    //Metod för att se om spelaren har rätt till bonuspoäng
    private boolean Bonus(){
        //om summan av ettor-sexor 63p eller högre, ger ett bonuspoäng
        if (sumLeft() > 62) {
            return true;
        }
        return false;
    }
    
    //Metod för att sortera värden
    public void BubbelSortera(int[]lista){
        for (int m = lista.length-1; m > 0; m--) {
            for (int n = 0; n < m; n++) {
                if (lista[n]>lista[n+1]) {
                    int temp = lista[n];
                    lista[n] = lista[n+1];
                    lista[n+1] = temp;
                }
            }
        }
    }
    
    //Metod för att unselect all dice buttons
    private void diceButtonUnselected(){
        tglbtnDice1.setSelected(false);
        tglbtnDice2.setSelected(false);
        tglbtnDice3.setSelected(false);
        tglbtnDice4.setSelected(false);
        tglbtnDice5.setSelected(false);
        
    }
    
    /* Metod för att räkna högra sidan av scorecard exkl. liten stege, stor stege och chans.
    * Undersöker hur frekvent varje tärningsvärde är inom tärningskastet, vilka är de två mest 
    * frekventa tärningsvärdena.
    * Undersöker om spelaren är kvalificerad för poäng inom kategorin och räknar poängen.
    */
    public int qualifyRight(String name){
        int sum = 0;
        int[]frekvens = new int[6];        //sortera efter nummervärde
        for (int i = 0; i < 5; i++) {   //fem tärningar att count
            frekvens[dicePosition[i]-1]++;         //räknar and store frekvens av dicevärde i frekvens-array(tärningsfrekvens av 1-6)
        }
        
        int topIdx1 = 0, topIdx2 = 0;   //hitta de två mest frekventa tärningsvärde, top1 & top2
        
        for (int i = 1; i < 6; i++){
            if (frekvens[i] > frekvens[topIdx1]) {    //hitta tärningsindex som är mest frekvent med högst värde
                topIdx2 = topIdx1;  
                topIdx1 = i;
            } else if (frekvens[i] > frekvens[topIdx2]) { //hitta tärningsindex som är nästmest frekvent med nästhögst värde
                topIdx2 = i;
            }
        }
        
        
        if (name.equals("yatzy") && frekvens[topIdx1] == 5) {
            // Yatzy                poäng = 50;
            sum = YATZY;
        } else if (name.equals("fyrtal") && frekvens[topIdx1] >= 4) {
            // Fyrtal               poäng = 4*(topIdx1+1)
            sum = 4*(topIdx1+1);
        } else if (name.equals("triss") || name.equals("kak") && frekvens[topIdx1] == 3) {
            if (name.equals("kak") && frekvens[topIdx2] == 2) {
                // Kåk              poäng = 3*(topIdx1+1) + 2*(topIdx2+1)
                sum = (3*(topIdx1+1) + 2*(topIdx2+1));
            } else if (name.equals("triss")){
                // Triss            poäng = 3*(topIdx1+1)
                sum = 3*(topIdx1+1);
            }
        } else if (name.equals("tvaPar") && frekvens[topIdx1] >= 2) {
            if (frekvens[topIdx2] == 2) {
                // Två par          poäng = 2*(topIdx1+1) + 2*(topIdx2+1)
                sum = (2*(topIdx1+1) + 2*(topIdx2+1));
            } else if (frekvens[topIdx1] == 4){
                    sum = (4*(topIdx1+1));
            }
        } else if (name.equals("ettPar") && frekvens[topIdx1] >= 2){     //poäng vid två par fel, väljer lägsta paret
            // Ett par          poäng = 2*(topIdx1+1)
            sum = 2*(topIdx1+1);
        }
        return sum;
    }
    
    private boolean txfLeftisAllFilled(){
            if (!txfEttor.getText().isEmpty() && 
                !txfTvaor.getText().isEmpty() && 
                !txfTreor.getText().isEmpty() && 
                !txfFyror.getText().isEmpty() && 
                !txfFemor.getText().isEmpty() && 
                !txfSexor.getText().isEmpty()) {
                return true;
            }
            else return false;
    }
    
    private boolean txfRightisAllFilled(){
        if (!txfEttPar.getText().isEmpty() && 
            !txfTvaPar.getText().isEmpty() && 
            !txfTriss.getText().isEmpty() && 
            !txfFyrtal.getText().isEmpty() && 
            !txfKak.getText().isEmpty() && 
            !txfLStege.getText().isEmpty() &&
            !txfSStege.getText().isEmpty() &&
            !txfChans.getText().isEmpty() &&
            !txfYatzy.getText().isEmpty()) {
                return true;
        } else return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yatzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yatzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yatzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yatzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yatzy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChans;
    private javax.swing.JButton btnEttPar;
    private javax.swing.JButton btnEttor;
    private javax.swing.JButton btnFemor;
    private javax.swing.JButton btnFyror;
    private javax.swing.JButton btnFyrtal;
    private javax.swing.JButton btnKak;
    private javax.swing.JButton btnKasta;
    private javax.swing.JButton btnLStege;
    private javax.swing.JButton btnSStege;
    private javax.swing.JButton btnSexor;
    private javax.swing.JButton btnStarta;
    private javax.swing.JButton btnTreor;
    private javax.swing.JButton btnTriss;
    private javax.swing.JButton btnTvaPar;
    private javax.swing.JButton btnTvaor;
    private javax.swing.JButton btnYatzy;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JLabel lblS2Left;
    private javax.swing.JLabel lblS2Right;
    private javax.swing.JToggleButton tglbtnDice1;
    private javax.swing.JToggleButton tglbtnDice2;
    private javax.swing.JToggleButton tglbtnDice3;
    private javax.swing.JToggleButton tglbtnDice4;
    private javax.swing.JToggleButton tglbtnDice5;
    private javax.swing.JTextField txfBonus;
    private javax.swing.JTextField txfBonusS2;
    private javax.swing.JTextField txfChans;
    private javax.swing.JTextField txfEttPar;
    private javax.swing.JTextField txfEttParS2;
    private javax.swing.JTextField txfEttor;
    private javax.swing.JTextField txfEttorS2;
    private javax.swing.JTextField txfFemmorS2;
    private javax.swing.JTextField txfFemor;
    private javax.swing.JTextField txfFyror;
    private javax.swing.JTextField txfFyrorS2;
    private javax.swing.JTextField txfFyrtal;
    private javax.swing.JTextField txfKak;
    private javax.swing.JTextField txfLStege;
    private javax.swing.JTextField txfSStege;
    private javax.swing.JTextField txfSexor;
    private javax.swing.JTextField txfSexorS2;
    private javax.swing.JTextField txfSumma;
    private javax.swing.JTextField txfSummaS2;
    private javax.swing.JTextField txfTotal;
    private javax.swing.JTextField txfTreor;
    private javax.swing.JTextField txfTreorS2;
    private javax.swing.JTextField txfTriss;
    private javax.swing.JTextField txfTvaPar;
    private javax.swing.JTextField txfTvaParS2;
    private javax.swing.JTextField txfTvaor;
    private javax.swing.JTextField txfTvaorS2;
    private javax.swing.JTextField txfYatzy;
    // End of variables declaration//GEN-END:variables
}
